### ISSUE TITLE
Version in docker image

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper-load-test#5]
Is the latest version already available as docker image? If not, should we print some kind of version info for `-h`?

**Comment by rokcarl** [comment]
I've already pushed the latest image to Docker Hub. There's no version info yet, but also the `graphhopper/load-testing` repo is private currently. However, anyone can build it for themselves using `make build`.

I'll add the version info inside.

Should we also open up the Docker Hub repo?

**Comment by karussell** [comment]
> Should we also open up the Docker Hub repo?

Yes, good idea.

**Comment by rokcarl** [comment]
The Docker Hub repo is open, unauthorized clients can `pull`, but can't `push`, which is what we want.
And I've created #13 for solving this issue.
